name: "Sueltame Bogota , tu ya sabes que no puedo parar."

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - sdk_name: "immortalwrt-sdk-25.12.0-rc2-x86-64_gcc-14.3.0_musl.Linux-x86_64"
          - project_name: "luci-app-pm"

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install Build Dependencies
        uses: mokanove/mokanove/actions/luci-env@main

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: ${{ matrix.sdk_name }}

      - name: Clone Source Code & Get Version
        uses: mokanove/mokanove/actions/clone@main
        with:
          sdk_name: ${{ matrix.project_name }}

      - name: Build!
        uses: mokanove/mokanove/actions/build@main
        with:
          sdk_name: ${{ matrix.sdk_name }}
          project_name: ${{ matrix.project_name }}


      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: ${{ matrix.sdk_name }}/bin/packages/**/*.apk
          body: |
            # 🚀 Release Notes
            - Separate the Action section.
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
